# Generated by Django 6.0 on 2026-01-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0003_message_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tags",
            field=models.ManyToManyField(related_name="messages", to="messenger.tag"),
        ),
    ]
